@echo off
cls
echo Upgradeing PC.
echo Upgradeing PC..
echo Upgradeing PC...
echo Upgradeing PC....
echo Upgradeing PC.....
echo Upgradeing PC......
echo Upgradeing PC.......
echo Upgradeing PC........
echo Upgradeing PC.........
echo Upgradeing PC..........
echo Upgradeing PC...........
echo Upgradeing PC............
echo Upgradeing PC.............
echo Upgradeing PC..............
echo Upgradeing PC...............
pause